// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpcWvfWTQxRn2ZOZmyiI2N-BWD-9u8P4',
    appId: '1:593862575380:web:c50dad874d00e60a052e01',
    messagingSenderId: '593862575380',
    projectId: 'locotour-5cdce',
    authDomain: 'locotour-5cdce.firebaseapp.com',
    storageBucket: 'locotour-5cdce.appspot.com',
    measurementId: 'G-N46ME808WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LT-pjRRT7zNiRTzboetK5eGKWjm8n0g',
    appId: '1:593862575380:android:52b3a468019cdc46052e01',
    messagingSenderId: '593862575380',
    projectId: 'locotour-5cdce',
    storageBucket: 'locotour-5cdce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qJa0hfXEGCjrCeLN9K2nfWZ6pr4CEY8',
    appId: '1:593862575380:ios:0269dcc19fa87a7a052e01',
    messagingSenderId: '593862575380',
    projectId: 'locotour-5cdce',
    storageBucket: 'locotour-5cdce.appspot.com',
    iosClientId: '593862575380-q7fro9dobq6pafoeg6k7goulvd72b4n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeCulturalRenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qJa0hfXEGCjrCeLN9K2nfWZ6pr4CEY8',
    appId: '1:593862575380:ios:0269dcc19fa87a7a052e01',
    messagingSenderId: '593862575380',
    projectId: 'locotour-5cdce',
    storageBucket: 'locotour-5cdce.appspot.com',
    iosClientId: '593862575380-q7fro9dobq6pafoeg6k7goulvd72b4n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeCulturalRenter',
  );
}
